### ISSUE TITLE
Create a debugging process for on-call

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-devops#29]
**Describe the use case**
Ideally, when things go down, either in our bootstrap servers and/or bots, we provide some sort of cookbook SREs and/or support can go through to isolate the most common cases to know when to escalate from L2 to L3.

**The feature**
Put together DEBUGGING.md inside `devops` to allow rota members to be able to take a look at things when systems are down.

**Comment by tolbrino** [comment]
Closing. Since there is no on-call support for our infrastructure, the original intent is missing.
