### ISSUE TITLE
Deploying CT nodes for `release/rio`

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-devops#35]
# Introduction

To test the first implementation of CT, we'll deploy a few instances of the `release/rio` CT version.

# Task Description

- [ ] Deploy a set of `release-rio` CT nodes for our testnet

**Comment by jjperezaguinaga** [comment]
We are pending https://github.com/hoprnet/hoprnet/pull/2541 which would create the last version to use for CT nodes for `release/rio`

**Comment by QYuQianchen** [comment]
It was deployed after the said PR. We will need to redeploy it after future fixes. (So leave it open ...)

**Comment by jjperezaguinaga** [comment]
Yeah, I'll move this to a checklist item, since we'll need to do this for each release.

**Comment by jjperezaguinaga** [comment]
Completed manually, and checklists created in #2573
